#!/usr/bin/bash

#echo "==> Run smoke test"
#../src/build/release/smoke_test

echo "==> python"
export PYTHONPATH=../build/pkg/usr/lib/python3.14/site-packages
export LD_LIBRARY_PATH=../build/release

uv run pytest -v -s test_ipa.py

