#!/usr/bin/bash
# 
# Installs libpatricia and the python module(s) into <dest-dir>
#
# NB 
# 1) Must be called after build is completed:
# 2) Must be called in top level (parallel with src, tests, meson.build, pyproject.toml etc)
#
# i.e. meson compile -C build/release && uv build --wheel
#
# do-install <destdir>
#
# target = clibs or pymods
#
set -euo pipefail

if (( $# < 1 )) ; then
    dest='build/pkg'
else
    dest="$1"
fi

# 
# ensure we have full path.
# 
pkgdir=$(realpath "$dest")

/usr/bin/meson install -C build/release --destdir "$pkgdir" > /dev/null

exit


