#!/usr/bin/bash
# 
# Installs libpatricia and the python module(s) into <dest-dir>
#
# NB 
# 1) Must be called after build is completed:
# 2) Must be called in top level (parallel with src, tests, meson.build, pyproject.toml etc)
#
# i.e. meson compile -C build/release && uv build --wheel
#
# do-install <destdir>
#
# target = clibs or pymods
#
if (( $# < 1 )) ; then
    echo "Missing args : <destdir>"
    exit 1
fi
dest="$1"

# 
# ensure we have full path.
# 
pkgdir=$(realpath "$dest")

/usr/bin/meson install -C build/release --destdir "$pkgdir" > /dev/null

sitedir=$(python -c "import site; print(site.getsitepackages()[0])")
installdir="${pkgdir}${sitedir}"
mkdir -p "$installdir"

uv_opts=(
    --python /usr/bin/python
    --system
    --no-build-isolation
    --link-mode=copy
    --compile-bytecode
    )

/usr/bin/uv pip install "${uv_opts[@]}" --target "$installdir" dist/*.whl
locks=(
    "$installdir"/patricia26/.lock 
    "$installdir"/.lock 
    "$installdir"/patricia26/uv.lock 
    "$installdir"/uv.lock 
    uv.lock)
/usr/bin/rm -rf "${locks[@]}"

#
# meson strips the /usr/lib/libpatricia26.so but not the puthon modules
#
if [[ -d "$installdir/patricia26"  ]] ; then
    /usr/bin/strip "$installdir"/patricia26/_patricia26*.so
fi
